-- ============================================================
-- RetailOS - Esquema de Base de Datos Supabase
-- ============================================================

-- Extensiones
create extension if not exists "pgcrypto";

-- ============================================================
-- STORES (Tiendas)
-- ============================================================
create table public.stores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  rfc text,
  direccion text,
  telefono text,
  email text,
  logo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.stores enable row level security;

-- ============================================================
-- USER PROFILES (Perfiles de usuario vinculados a auth.users)
-- ============================================================
create table public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nombre text not null,
  rol text not null check (rol in ('admin', 'cajero', 'almacenista', 'gerente')) default 'cajero',
  store_id bigint references public.stores(id) on delete set null,
  avatar_url text,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.user_profiles enable row level security;

-- ============================================================
-- CATEGORIES
-- ============================================================
create table public.categories (
  id bigint generated by default as identity primary key,
  nombre text not null,
  color text default '#628141',
  store_id bigint references public.stores(id) on delete cascade,
  created_at timestamptz default now()
);

alter table public.categories enable row level security;

-- ============================================================
-- SUPPLIERS (Proveedores)
-- ============================================================
create table public.suppliers (
  id bigint generated by default as identity primary key,
  nombre text not null,
  contacto text,
  telefono text,
  email text,
  direccion text,
  store_id bigint references public.stores(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.suppliers enable row level security;

-- ============================================================
-- PRODUCTS
-- ============================================================
create table public.products (
  id bigint generated by default as identity primary key,
  sku text,
  codigo_barras text,
  nombre text not null,
  categoria text,
  category_id bigint references public.categories(id) on delete set null,
  precio_compra numeric(10,2) default 0,
  precio_venta numeric(10,2) default 0,
  existencia numeric(10,2) default 0,
  stock_min numeric(10,2) default 10,
  proveedor_id bigint references public.suppliers(id) on delete set null,
  store_id bigint references public.stores(id) on delete cascade,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Índices
create index idx_products_store on public.products(store_id);
create index idx_products_barcode on public.products(codigo_barras);
create index idx_products_category on public.products(category_id);

alter table public.products enable row level security;

-- ============================================================
-- INVENTORY MOVEMENTS
-- ============================================================
create table public.inventory_movements (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.products(id) on delete cascade,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste')),
  cantidad numeric(10,2) not null,
  motivo text,
  referencia text,
  user_id uuid references auth.users(id),
  store_id bigint references public.stores(id) on delete cascade,
  created_at timestamptz default now()
);

create index idx_movements_product on public.inventory_movements(producto_id);
create index idx_movements_store on public.inventory_movements(store_id);
create index idx_movements_created on public.inventory_movements(created_at desc);

alter table public.inventory_movements enable row level security;

-- ============================================================
-- SALES (Ventas)
-- ============================================================
create table public.sales (
  id bigint generated by default as identity primary key,
  folio text not null,
  cliente text default 'Cliente general',
  subtotal numeric(10,2) default 0,
  iva numeric(10,2) default 0,
  total numeric(10,2) default 0,
  metodo_pago text not null check (metodo_pago in ('efectivo', 'transferencia', 'terminal')),
  user_id uuid references auth.users(id),
  store_id bigint references public.stores(id) on delete cascade,
  created_at timestamptz default now()
);

create index idx_sales_store on public.sales(store_id);
create index idx_sales_created on public.sales(created_at desc);
create index idx_sales_date on public.sales(date(created_at));

alter table public.sales enable row level security;

-- ============================================================
-- SALE ITEMS
-- ============================================================
create table public.sale_items (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.sales(id) on delete cascade,
  producto_id bigint references public.products(id) on delete set null,
  nombre text not null,
  precio numeric(10,2) not null,
  qty numeric(10,2) not null,
  subtotal numeric(10,2) not null
);

create index idx_sale_items_venta on public.sale_items(venta_id);

alter table public.sale_items enable row level security;

-- ============================================================
-- AI CHATS (Historial de conversaciones IA)
-- ============================================================
create table public.ai_chats (
  id bigint generated by default as identity primary key,
  title text,
  user_id uuid references auth.users(id),
  store_id bigint references public.stores(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.ai_chats enable row level security;

create table public.ai_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint references public.ai_chats(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

create index idx_ai_messages_chat on public.ai_messages(chat_id);

alter table public.ai_messages enable row level security;

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  descripcion text,
  tipo text default 'info',
  leida boolean default false,
  created_at timestamptz default now()
);

create index idx_notifications_user on public.notifications(user_id);

alter table public.notifications enable row level security;

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

-- Actualiza updated_at automáticamente
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at before update on public.stores
  for each row execute function public.handle_updated_at();
create trigger set_updated_at before update on public.user_profiles
  for each row execute function public.handle_updated_at();
create trigger set_updated_at before update on public.suppliers
  for each row execute function public.handle_updated_at();
create trigger set_updated_at before update on public.products
  for each row execute function public.handle_updated_at();

-- Crea perfil automáticamente al registrarse
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_profiles (id, email, nombre, rol)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'nombre', 'Usuario'), 'cajero');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- Stores: solo admin puede modificar, todos ven su tienda
create policy "Users can view their store" on public.stores
  for select using (
    id in (select store_id from public.user_profiles where id = auth.uid())
  );

-- Products: multi-tenant por store
create policy "Users can view products from their store" on public.products
  for select using (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

create policy "Users can insert products" on public.products
  for insert with check (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

create policy "Users can update products" on public.products
  for update using (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

-- Sales
create policy "Users can view their store sales" on public.sales
  for select using (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

create policy "Users can insert sales" on public.sales
  for insert with check (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

-- Sale items
create policy "Users can view sale items" on public.sale_items
  for select using (
    venta_id in (select id from public.sales where store_id in (select store_id from public.user_profiles where id = auth.uid()))
  );

create policy "Users can insert sale items" on public.sale_items
  for insert with check (
    venta_id in (select id from public.sales where store_id in (select store_id from public.user_profiles where id = auth.uid()))
  );

-- Inventory movements
create policy "Users can view movements" on public.inventory_movements
  for select using (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

create policy "Users can insert movements" on public.inventory_movements
  for insert with check (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

-- Categories
create policy "Users can view categories" on public.categories
  for select using (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );

-- Suppliers
create policy "Users can view suppliers" on public.suppliers
  for select using (
    store_id in (select store_id from public.user_profiles where id = auth.uid())
  );
